#!/bin/sh

APPDIR=`pwd`
BASEDIR=`dirname $0`/..
BASEDIR=`(cd "$BASEDIR"; pwd)`

export GEM_HOME="$APPDIR"/.gems
export GEM_PATH=$GEM_HOME
export PATH="$GEM_PATH"/bin:$PATH
export BUNDLE_GEMFILE="$APPDIR"/Jemfile

./target/bin/jruby "$@"